version: "3.7"
services:
  fuzzy-disco:
    container_name: fuzzy-disco
    image: ghcr.io/altair-bueno/fuzzy-disco:master
    ports:
      - "8000:8000"
    depends_on:
      - "redis-cache"
      - "mongodb"
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/
      REDIS_URI: redis://redis-cache:6379/
    volumes:
      - fuzzy-disco-storage:/fuzzy-disco/media
  redis-cache:
    container_name: redis-cache
    build: redis/
    ports:
      - "127.0.0.1:6379:6379"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-storage:/data/db
volumes:
  mongodb-storage:
  fuzzy-disco-storage: