version: "3.7"
services:
  fuzzy-disco:
    container_name: fuzzy-disco
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "redis-cache"
      - "mongodb"
  redis-cache:
    container_name: redis-cache
    build: redis/
    ports:
      - "127.0.0.1:6379:6379"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      - mongodb-storage:/data/db
volumes:
  mongodb-storage: