name: Test docker-compose
env:
  at: 127.0.0.1:8000
on:
  push:
    branches:
      - release
      - master
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: docker-compose up -d
        name: Building service
      - name: Waiting server to startup
        run: sleep 300
      - run: "curl http://${{ env.at }}"
        name: Checking if webpage is up
      - name: api client testing
        run: |
          python -m pip install requests
          python test.py
        working-directory: disco-core/tests/
      #- run: "curl http://127.0.0.1:${{ env.port }}/api/posts"
